// Region descriptions keyed by Allen CCF allenId.
// Descriptions focus on function and cellular identity; connectivity is shown
// interactively by the map itself.

export const REGION_DESCRIPTIONS = {
  // ── Isocortex ──────────────────────────────────────────────────────────────
  16:  "Layer 6b of the isocortex. The deepest neocortical layer; coordinates thalamocortical dialogue.",
  39:  "Anterior cingulate area, dorsal part. Involved in cognitive control, attention, error monitoring, and conflict resolution; a key node of the prefrontal executive network.",
  48:  "Anterior cingulate area, ventral part. Processes affective and motivational aspects of pain and decision-making.",
  104: "Agranular insular area, dorsal part. Involved in interoception, motor preparation, and sensory-motor integration.",
  111: "Agranular insular area, posterior part. Integrates visceral, taste, and somatic information; important for body-state awareness and autonomic regulation.",
  119: "Agranular insular area, ventral part. Involved in gustatory and visceral processing; contributes to the affective valuation of interoceptive and sensory stimuli.",
  1011:"Dorsal auditory area. Higher-order auditory cortex involved in auditory object recognition and spatial processing.",
  1002:"Primary auditory cortex. Performs frequency-specific spectrotemporal analysis of sound; organized tonotopically.",
  1027:"Posterior auditory area. Higher-order auditory cortex involved in processing complex acoustic features and auditory memory.",
  1018:"Ventral auditory area. Secondary auditory cortex involved in auditory integration and discrimination.",
  814: "Dorsal peduncular area. A medial prefrontal region involved in visceral and autonomic regulation.",
  895: "Ectorhinal area. Parahippocampal cortex; an intermediate relay between polymodal sensory regions and the entorhinal cortex.",
  918: "Entorhinal area, lateral part. Primary cortical gateway to the hippocampus; the main source of the perforant path.",
  926: "Entorhinal area, medial part (dorsal zone). Encodes spatial and contextual information; integrates self-motion signals and contains grid cells critical for navigation.",
  934: "Entorhinal area, medial part (ventral zone). Part of the parahippocampal region; involved in spatial and contextual encoding alongside the dorsal medial entorhinal cortex.",
  1057:"Gustatory areas. Integrate flavor, texture, and hedonic information to guide ingestion decisions.",
  44:  "Infralimbic area. A ventromedial prefrontal region involved in habit formation, fear extinction, and autonomic regulation.",
  985: "Primary motor cortex. Directly controls voluntary movement; organized somatotopically with the hindlimb medial and forelimb lateral.",
  993: "Secondary motor cortex. Involved in motor planning, sequencing, and coordination.",
  731: "Orbital area, medial part. Part of orbitofrontal cortex; encodes reward value and expected outcomes; critical for flexible, value-guided decision-making.",
  723: "Orbital area, lateral part. Part of orbitofrontal cortex; integrates sensory qualities with reward history; involved in credit assignment and reversal learning.",
  738: "Orbital area, ventral part. Part of orbitofrontal cortex involved in olfactory and taste processing and reward-based evaluation of food stimuli.",
  746: "Orbital area, ventrolateral part. Part of orbitofrontal cortex integrating multimodal sensory information for reward-guided behavior.",
  922: "Perirhinal area. Parahippocampal cortex essential for object recognition memory and novelty detection.",
  961: "Piriform area. Primary olfactory cortex; encodes odor identity.",
  972: "Prelimbic area. Dorsomedial prefrontal cortex involved in working memory, fear expression, and goal-directed decision-making.",
  879: "Retrosplenial area, dorsal part. Involved in spatial navigation, contextual memory, and integration of allocentric and egocentric reference frames.",
  886: "Retrosplenial area, ventral part. Involved in spatial and contextual memory consolidation; bridges hippocampal and neocortical memory systems.",
  894: "Retrosplenial area, lateral agranular part. Part of retrosplenial cortex; participates in spatial processing and head-direction signal integration.",
  329: "Primary somatosensory area, barrel field. Processes whisker-related tactile information; each barrel corresponds to a single facial whisker, making this a model for cortical topographic organization.",
  337: "Primary somatosensory area, lower limb. Processes tactile and proprioceptive input from the hindlimb.",
  345: "Primary somatosensory area, mouth. Processes orofacial somatosensory input including touch and pressure around the mouth.",
  353: "Primary somatosensory area, nose. Processes nasal tactile input.",
  361: "Primary somatosensory area, trunk. Processes somatosensory input from the body trunk and thorax.",
  369: "Primary somatosensory area, upper limb. Processes tactile and proprioceptive input from the forelimb.",
  378: "Supplemental somatosensory area. Secondary somatosensory cortex integrating bilateral somatosensory information; contributes to tactile discrimination and cross-modal processing.",
  541: "Temporal association areas. Multimodal association cortex involved in object recognition, auditory processing, and long-term declarative memory.",
  677: "Visceral area. Integrates body-state signals; participates in autonomic regulation.",
  312782546: "Anterior visual area. Higher-order visual cortex processing optic flow and wide-field motion; involved in visual navigation.",
  402: "Anterolateral visual area. Higher-order visual cortex; processes motion and spatial relationships in the visual scene.",
  394: "Anteromedial visual area. Higher-order visual cortex integrating motion and spatial navigation signals.",
  409: "Lateral visual area. Secondary visual cortex processing visual detail and object features.",
  385: "Primary visual cortex. First cortical processing stage of vision; encodes orientation, spatial frequency, and contrast; organized retinotopically.",
  425: "Posterolateral visual area. Higher-order visual cortex involved in visuospatial processing.",
  533: "Posteromedial visual area. Higher-order visual area involved in spatial processing and visual navigation.",
  417: "Rostrolateral visual area. Higher-order visual cortex; part of the rodent visual cortical hierarchy.",

  // ── Hippocampal formation ──────────────────────────────────────────────────
  382: "Field CA1 of the hippocampus. Critical for episodic memory encoding and spatial map representation.",
  423: "Field CA2 of the hippocampus. Involved in social memory and temporal context coding; highly resistant to excitotoxic insult.",
  463: "Field CA3 of the hippocampus. Performs pattern completion via recurrent collaterals; rapidly encodes new associative memories.",
  726: "Dentate gyrus. Performs pattern separation of incoming signals; generates new granule cells throughout adult life (adult neurogenesis), contributing to memory clearance and context discrimination.",
  502: "Subiculum. Main output of the hippocampus; involved in spatial navigation and memory retrieval.",
  1084:"Presubiculum. Important for maintaining the spatial orientation framework used by entorhinal grid cells.",
  1037:"Postsubiculum. Contains head-direction cells; critical for spatial navigation.",
  843: "Parasubiculum. Part of the parahippocampal region; contains grid cells and border cells; contributes to the spatial metric used in navigation.",
  982: "Fasciola cinerea. A rudimentary cortical strip of the hippocampal formation overlying the dentate gyrus.",
  19:  "Induseum griseum. A vestigial cortical structure overlying the dorsal corpus callosum; considered a rudimentary part of the hippocampal formation.",

  // ── Amygdala ───────────────────────────────────────────────────────────────
  303: "Basolateral amygdalar nucleus, anterior part. A key site for fear conditioning and reward learning.",
  311: "Basolateral amygdalar nucleus, posterior part. Processes aversive and emotionally salient stimuli; drives fear responses.",
  451: "Basolateral amygdalar nucleus, ventral part. Part of the basolateral complex involved in emotional memory and reward.",
  327: "Basomedial amygdalar nucleus, anterior part. Involved in olfactory-based social and emotional responses.",
  334: "Basomedial amygdalar nucleus, posterior part. Processes pheromone and olfactory signals; contributes to species-specific social and reproductive behavior.",
  544: "Central amygdalar nucleus, capsular part. Part of the central amygdala output system; involved in regulating behavioral and autonomic fear responses.",
  551: "Central amygdalar nucleus, lateral part. Serves as an integration zone for fear acquisition and modulation.",
  559: "Central amygdalar nucleus, medial part. Primary output of the amygdala; controls freezing behavior, analgesia, and autonomic stress responses.",
  403: "Medial amygdalar nucleus. Critical for sex-specific and species-specific social, territorial, and reproductive behavior; processes pheromone signals.",
  131: "Lateral amygdalar nucleus. The initial site of Pavlovian fear conditioning; stores fear-related sensory associations.",
  639: "Cortical amygdalar area, anterior part. Involved in olfactory processing and odor-guided behavior.",
  655: "Cortical amygdalar area, posterior lateral zone. Processes olfactory information; contributes to chemosensory-based social and reproductive behavior.",
  663: "Cortical amygdalar area, posterior medial zone. Involved in pheromone processing and reproductive behavior regulation.",
  780: "Posterior amygdalar nucleus. Part of the amygdaloid complex involved in multimodal sensory integration and defensive behaviors.",
  788: "Piriform-amygdalar area. Transition zone between piriform cortex and the amygdala; involved in olfactory processing.",
  23:  "Anterior amygdalar area. Transitional zone at the anterior pole of the amygdala; processes olfactory and other sensory signals.",
  292: "Bed nucleus of the accessory olfactory tract. Small nucleus associated with the accessory olfactory system and pheromone signal processing.",
  1105:"Intercalated amygdalar nucleus. Small clusters of GABAergic neurons situated between the basolateral and central amygdala; critical for fear extinction.",

  // ── Striatum and basal ganglia ─────────────────────────────────────────────
  672: "Caudoputamen. Dorsal striatum; the main input nucleus of the basal ganglia for motor control; involved in habit formation and procedural learning.",
  56:  "Nucleus accumbens. Ventral striatum; the core interface between limbic and motor systems; critical for reward processing, motivation, and reinforcement learning.",
  754: "Olfactory tubercle. Part of the ventral striatum; integrates olfactory signals with motivational state.",
  998: "Fundus of striatum. Transition zone at the base of the striatum connecting dorsal and ventral striatal territories.",
  1022:"Globus pallidus, external segment. Part of the indirect basal ganglia pathway; serves as an integration hub in basal ganglia circuitry.",
  1031:"Globus pallidus, internal segment. Primary output nucleus of the basal ganglia; tonically inhibits the motor thalamus to gate movement.",
  470: "Subthalamic nucleus. The only glutamatergic nucleus in the basal ganglia; a clinically critical target for deep brain stimulation in Parkinson's disease.",
  374: "Substantia nigra, compact part. Contains dopaminergic neurons of the nigrostriatal pathway; encodes reward prediction errors; degeneration of these neurons is the hallmark of Parkinson's disease.",
  381: "Substantia nigra, reticular part. Shares circuitry with GPi as an output nucleus of the basal ganglia; tonically inhibits motor gating of saccadic eye movements and voluntary movement.",

  // ── Thalamus ───────────────────────────────────────────────────────────────
  64:  "Anterodorsal nucleus. Part of the anterior thalamic group; contains robust head-direction cells; a critical node in the circuit for spatial orientation and navigation.",
  255: "Anteroventral nucleus. Part of the anterior thalamic group; part of the Papez circuit; involved in episodic memory and spatial navigation.",
  575: "Central lateral nucleus. Intralaminar thalamic nucleus; involved in arousal, attention, and motor control.",
  599: "Central medial nucleus. Intralaminar thalamic nucleus; involved in attention, arousal, and sensorimotor gating.",
  59:  "Intermediodorsal nucleus. Medial thalamic nucleus involved in memory and limbic functions.",
  1104:"Anteromedial nucleus, ventral part. Subdivision of the anteromedial thalamic nucleus; part of the anterior thalamic group involved in the Papez circuit and spatial memory.",
  1113:"Interanterodorsal nucleus. Part of the anterior thalamic complex involved in spatial memory and limbic circuits.",
  1120:"Interanteromedial nucleus. Part of the anterior thalamic complex; contributes to spatial memory and the Papez memory circuit.",
  27:  "Intergeniculate leaflet. Part of the lateral geniculate complex; contains neuropeptide Y neurons; involved in non-image-forming visual functions including circadian photoentrainment.",
  155: "Lateral dorsal nucleus. Anterior thalamic group nucleus; contains head-direction cells; involved in spatial navigation and memory as part of the extended hippocampal system.",
  170: "Dorsal lateral geniculate nucleus. Primary visual thalamic relay; organized in retinotopic laminae corresponding to different retinal ganglion cell types.",
  178: "Ventral lateral geniculate nucleus. Non-image-forming visual nucleus; involved in circadian rhythm regulation, photic modulation of locomotion, and pupillary responses.",
  186: "Lateral habenula. Part of the habenular complex; encodes negative prediction errors in response to absent or unexpected rewards.",
  218: "Lateral posterior nucleus. Higher-order thalamic nucleus involved in visuospatial processing and multisensory integration.",
  362: "Mediodorsal nucleus. Prefrontal thalamic nucleus involved in working memory, attention, and cognitive control.",
  1072:"Medial geniculate complex, dorsal part. Higher-order auditory thalamic nucleus involved in multimodal integration and auditory fear conditioning.",
  1088:"Medial geniculate complex, medial part. Multimodal thalamic nucleus involved in auditory fear learning and arousal.",
  1079:"Medial geniculate complex, ventral part. Primary auditory thalamic relay; organized tonotopically.",
  483: "Medial habenula. Part of the habenular complex; contains substance P and acetylcholine neurons; involved in stress responses, anxiety, aversion, and mood regulation.",
  907: "Paracentral nucleus. Intralaminar thalamic nucleus involved in nociception, arousal, and motor control.",
  930: "Parafascicular nucleus. Intralaminar thalamic nucleus; involved in attention, nociception, and motor sequence learning.",
  1020:"Posterior complex of the thalamus. Higher-order thalamic nucleus for nociceptive and somatosensory processing.",
  1029:"Posterior limiting nucleus of the thalamus. Part of the posterior thalamic complex; involved in multisensory processing.",
  15:  "Parataenial nucleus. Small anterior thalamic nucleus involved in limbic and motivational functions.",
  149: "Paraventricular nucleus of the thalamus. Midline thalamic nucleus; a critical relay for stress signals and arousal states; involved in limbic-striatal integration.",
  181: "Nucleus of reuniens. Midline thalamic nucleus involved in working memory, spatial navigation, and extinction of conditioned fear.",
  189: "Rhomboid nucleus. Midline thalamic nucleus involved in limbic and cognitive functions.",
  262: "Reticular nucleus of the thalamus. Inhibitory GABAergic nucleus surrounding the thalamus; gates thalamic relay; critical for thalamocortical oscillations, selective attention, and sleep spindles.",
  366: "Submedial nucleus of the thalamus. Part of the ventral thalamic group involved in processing orofacial nociceptive information.",
  629: "Ventral anterior-lateral complex. Motor thalamus coordinating basal ganglia and cerebellar output for voluntary movement.",
  685: "Ventral medial nucleus. Motor thalamus involved in gating voluntary movement initiation.",
  718: "Ventral posterolateral nucleus. Somatosensory thalamic relay for the body; organized topographically.",
  725: "Ventral posterolateral nucleus, parvicellular part. Somatosensory thalamic subdivision for deep tissue and proprioceptive signals from the body.",
  733: "Ventral posteromedial nucleus. Somatosensory thalamic relay for the face; organized topographically.",
  741: "Ventral posteromedial nucleus, parvicellular part. Thalamic relay for gustatory information.",
  325: "Suprageniculate nucleus. Thalamic nucleus involved in multisensory processing.",
  321: "Subgeniculate nucleus. Small thalamic nucleus located beneath the lateral geniculate; involved in visual thalamic processing.",
  367: "TBD",

  // ── Septal area ────────────────────────────────────────────────────────────
  564: "Medial septal nucleus. Contains cholinergic and GABAergic neurons; paces the hippocampal theta rhythm; critical for spatial memory, attention, and navigation.",
  250: "Lateral septal nucleus, caudal part. Involved in stress responses, anxiety regulation, and social behavior.",
  258: "Lateral septal nucleus, rostral part. Involved in stress responses, aggression, and social recognition memory.",
  266: "Lateral septal nucleus, ventral part. Involved in autonomic and neuroendocrine regulation and HPA axis activity.",
  596: "Diagonal band nucleus. Contains cholinergic neurons; important for attention, memory, and olfactory processing.",
  310: "Septofimbrial nucleus. Part of the septal area involved in hippocampo-septal interactions and limbic memory circuitry.",
  333: "Septohippocampal nucleus. Part of the septal complex containing cholinergic neurons involved in regulating hippocampal activity.",
  581: "Triangular nucleus of septum. Small nucleus within the septal complex; involved in limbic regulation.",
  287: "Bed nucleus of the anterior commissure. Small nucleus associated with the anterior commissure involved in limbic circuitry.",
  351: "Bed nuclei of the stria terminalis. Extended amygdala structure involved in autonomic and neuroendocrine stress responses; critical for anxiety, fear, and social behavior.",
  50:  "Precommissural nucleus. Small nucleus in the septal region associated with the anterior commissure; TBD specific function.",

  // ── Hypothalamus ───────────────────────────────────────────────────────────
  72:  "Anterodorsal preoptic nucleus. Part of the preoptic area; involved in thermoregulation and sleep regulation.",
  80:  "Anterior hypothalamic area. Involved in temperature regulation, defensive behavior, and integration of homeostatic stress responses.",
  88:  "Anterior hypothalamic nucleus. Involved in thermoregulation and defensive behaviors; integrates somatosensory and stress signals.",
  223: "Arcuate hypothalamic nucleus. Contains key neuroendocrine and metabolic neurons including NPY/AgRP (hunger-promoting) and POMC/CART (satiety-promoting) neurons; regulates food intake, energy balance, growth hormone release, and reproduction.",
  263: "Anteroventral preoptic nucleus. Part of the preoptic area involved in sleep regulation, thermoregulation, and reproductive behavior.",
  272: "Anteroventral periventricular nucleus. Sexually dimorphic nucleus in the preoptic region; critical for generating the preovulatory LH surge that triggers ovulation.",
  830: "Dorsomedial hypothalamic nucleus. Involved in circadian control of feeding, body weight, and stress responses; regulates sympathetic outflow.",
  804: "Fields of Forel. Fiber tracts and associated neurons at the junction of the hypothalamus and midbrain; involved in motor coordination.",
  194: "Lateral hypothalamic area. Contains orexin/hypocretin and melanin-concentrating hormone neurons; regulates arousal, feeding, sleep-wake transitions, and reward.",
  210: "Lateral mammillary nucleus. Part of the mammillary body; involved in spatial navigation.",
  452: "Median preoptic nucleus. Involved in thermoregulation, fluid homeostasis, and sleep; contains osmosensitive neurons.",
  491: "Medial mammillary nucleus. Part of the Papez circuit; critical for episodic memory and spatial navigation.",
  732: "Medial mammillary nucleus, median part. A subdivision of the medial mammillary nucleus involved in memory and navigation circuits.",
  515: "Medial preoptic nucleus. Critical for male sexual behavior, parental behavior, and thermoregulation; contains sexually dimorphic nuclei regulated by gonadal hormones.",
  523: "Medial preoptic area. Integrates gonadal hormone signals to regulate reproductive behavior, thermoregulation, and sleep; major site of testosterone action.",
  531: "Medial pretectal area. Part of the pretectal complex involved in visual reflexes and the control of pupil diameter.",
  946: "Posterior hypothalamic nucleus. Involved in thermogenesis, arousal, and autonomic regulation; integrates thermoregulatory and behavioral state signals.",
  980: "Dorsal premammillary nucleus. A key node for processing threat and predator stress; involved in organizing defensive behavior.",
  1004:"Ventral premammillary nucleus. Involved in reproductive behavior and gonadotropin regulation.",
  38:  "Paraventricular hypothalamic nucleus. Contains CRH, vasopressin, and oxytocin neurons; central regulator of the HPA stress axis, autonomic nervous system, and neuroendocrine function.",
  63:  "Paraventricular hypothalamic nucleus, descending division. Regulates sympathetic and parasympathetic outflow and cardiovascular function.",
  30:  "Periventricular hypothalamic nucleus, anterior part. Contains somatostatin neurons inhibiting growth hormone release; involved in neuroendocrine regulation.",
  118: "Periventricular hypothalamic nucleus, intermediate part. Contains dopaminergic neurons regulating prolactin release; part of the tuberoinfundibular dopamine system.",
  126: "Periventricular hypothalamic nucleus, posterior part. Involved in neuroendocrine regulation and reproductive control.",
  133: "Periventricular hypothalamic nucleus, preoptic part. Contains neuroendocrine neurons involved in reproductive and autonomic regulation.",
  173: "Retrochiasmatic area. Transition zone between the caudal hypothalamus and the optic chiasm region; involved in neuroendocrine integration.",
  347: "Subparaventricular zone. Region immediately adjacent to the PVH; involved in circadian regulation of sleep, feeding, and autonomic rhythms.",
  286: "Suprachiasmatic nucleus. Master circadian pacemaker; receives photic input and generates 24-hour biological rhythms.",
  390: "Supraoptic nucleus. Contains magnocellular neurons producing vasopressin and oxytocin that are released directly into the bloodstream; regulates water balance, blood pressure, and social bonding.",
  525: "Supramammillary nucleus. Paces hippocampal theta rhythms; involved in spatial memory and sensorimotor integration.",
  614: "Tuberal nucleus. Part of the hypothalamic tuberal region; involved in reproductive and metabolic regulation.",
  1126:"Tuberomammillary nucleus, dorsal part. Contains histaminergic neurons promoting wakefulness; targeted by sedating antihistamines.",
  1:   "Tuberomammillary nucleus, ventral part. Contains histaminergic neurons involved in promoting arousal and wakefulness; part of the ascending arousal system.",
  693: "Ventromedial hypothalamic nucleus. Involved in satiety signaling, defensive behavior, and sexual behavior; contains dense estrogen receptors; a key node for glucose sensing and energy homeostasis.",
  689: "Ventrolateral preoptic nucleus. Contains galanin/GABA neurons that actively promote sleep; the main 'sleep switch' in the brain.",
  763: "Vascular organ of the lamina terminalis. Circumventricular organ lacking a blood-brain barrier; detects plasma osmolality and circulating angiotensin II to regulate fluid balance and thirst.",
  338: "Subfornical organ. Circumventricular organ without a blood-brain barrier; detects circulating hormones including angiotensin II and relaxin; controls thirst, salt appetite, and fluid homeostasis.",
  1109:"Parastrial nucleus. Small nucleus adjacent to the stria terminalis; involved in neuroendocrine signaling.",
  1124:"Suprachiasmatic preoptic nucleus. Part of the preoptic area adjacent to the SCN; involved in circadian-regulated reproductive behavior.",

  // ── Olfactory system ───────────────────────────────────────────────────────
  507: "Main olfactory bulb. First central relay of olfactory information; performs initial odor processing and spatial mapping.",
  151: "Accessory olfactory bulb. Processes pheromone signals from the vomeronasal organ; involved in social and reproductive behavior.",
  159: "Anterior olfactory nucleus. Early olfactory processing station; involved in olfactory memory and discrimination.",
  566: "Postpiriform transition area. Transition zone between piriform cortex and the amygdala; part of the primary olfactory cortex.",
  619: "Nucleus of the lateral olfactory tract. Part of the primary olfactory cortex.",
  597: "Taenia tecta, dorsal part. Hippocampal rudiment overlying the olfactory bulb; involved in olfactory processing.",
  605: "Taenia tecta, ventral part. Part of the olfactory cortex; involved in processing olfactory information.",

  // ── Claustrum and related ──────────────────────────────────────────────────
  583: "Claustrum. Thin sheet of neurons with dense cortical connectivity; proposed to coordinate cortical activity across sensory modalities and may play a role in conscious perception.",
  952: "Endopiriform nucleus, dorsal part. Deep layer of olfactory cortex; highly susceptible to seizure activity and involved in olfactory processing.",
  966: "Endopiriform nucleus, ventral part. Deep endopiriform region involved in olfactory processing.",
  342: "Substantia innominata. Contains the nucleus basalis of Meynert with cholinergic neurons widely distributed to the cerebral cortex; critical for attention, learning, and memory; degeneration of these neurons contributes to Alzheimer's disease.",
  298: "Magnocellular nucleus. Contains large cholinergic neurons; part of the basal forebrain cholinergic system supporting attention and memory.",

  // ── Midbrain ───────────────────────────────────────────────────────────────
  795: "Periaqueductal gray. Surrounds the cerebral aqueduct; a hub for integrating and coordinating responses to pain, threat, and stress; contains opioid-sensitive neurons mediating analgesia; organizes vocalization, reproductive behavior, and defensive responses.",
  214: "Red nucleus. Contains magnocellular (rubrospinal) and parvicellular (rubro-olivary) neurons; the magnocellular division is the origin of the rubrospinal tract for limb movement control.",
  246: "Midbrain reticular nucleus, retrorubral area. Located caudal to the red nucleus; contains dopaminergic A8 group neurons; involved in motor control and reward processing.",
  128: "Midbrain reticular nucleus. Brainstem motor region involved in locomotion, postural control, and arousal; an important origin of reticulospinal fibers.",
  616: "Cuneiform nucleus. Part of the mesencephalic locomotor region; stimulation elicits locomotion; coordinates locomotor rhythm initiation.",
  231: "Anterior tegmental nucleus. Small midbrain tegmental nucleus; involved in limbic and autonomic regulation.",
  880: "Dorsal tegmental nucleus. Contains head-direction cells; part of the Papez-adjacent circuit for spatial navigation.",
  100: "Interpeduncular nucleus. Involved in stress responses, anxiety, circadian rhythms, and the aversive effects of nicotine.",
  162: "Laterodorsal tegmental nucleus. Contains cholinergic neurons involved in REM sleep generation, arousal, and reward.",
  1052:"Pedunculopontine nucleus. Contains cholinergic and glutamatergic neurons involved in movement initiation, arousal, and gait control; part of the mesencephalic locomotor region; degeneration contributes to gait freezing in Parkinson's disease.",
  749: "Ventral tegmental area. Contains dopaminergic neurons of the mesolimbic and mesocortical systems; critical for reinforcement learning, addiction, and motivated behavior.",
  591: "Central linear nucleus raphe. Contains dopaminergic neurons near the ventral tegmental area; involved in behavioral and cardiovascular regulation.",
  679: "Superior central nucleus raphe. Contains serotonergic neurons; involved in anxiety, depression, and associative learning.",
  872: "Dorsal raphe nucleus. The largest serotonergic nucleus in the brain; regulates mood, anxiety, sleep-wake cycles, and appetite; the primary target of SSRI antidepressants.",
  12:  "Interfascicular nucleus raphe. Contains dopaminergic neurons adjacent to the fasciculus retroflexus near the VTA; involved in limbic and reward regulation.",
  197: "Rostral linear nucleus raphe. Contains serotonergic and dopaminergic neurons; involved in limbic mood and motivation regulation.",
  1044:"Peripeduncular nucleus. Located adjacent to the cerebral peduncle; involved in acoustic and limbic processing.",
  1077:"Perireunensis nucleus. Small thalamic nucleus adjacent to the nucleus of reuniens; TBD specific function.",
  609: "Subparafascicular area. Located adjacent to the parafascicular nucleus; involved in multimodal thalamic integration.",
  414: "Subparafascicular nucleus, magnocellular part. Thalamic nucleus involved in multimodal sensory-limbic integration.",
  422: "Subparafascicular nucleus, parvicellular part. Involved in multimodal thalamic processing.",
  356: "Preparasubthalamic nucleus. Small nucleus adjacent to the subthalamic region; TBD specific function.",
  364: "Parasubthalamic nucleus. Small nucleus adjacent to the STN involved in hypothalamic-basal ganglia interactions.",
  757: "Ventral tegmental nucleus. Small tegmental nucleus involved in spatial orientation and navigation; part of the circuit linking mammillary bodies and the dorsal tegmentum.",

  // ── Raphe and pontine tegmentum ────────────────────────────────────────────
  206: "Nucleus raphe magnus. Contains serotonergic neurons; a key node of the descending pain-control system that produces stimulation-produced analgesia.",
  222: "Nucleus raphe obscurus. Serotonergic nucleus in the medullary raphe; involved in somatic motor facilitation, autonomic regulation, and control of respiratory rhythm.",
  230: "Nucleus raphe pallidus. Contains serotonergic neurons; involved in thermoregulation via sympathetic pathways to brown adipose tissue and skin vasculature.",
  238: "Nucleus raphe pontis. Pontine raphe nucleus; involved in modulation of cerebellar and spinal motor activity.",

  // ── Parabrachial and related ───────────────────────────────────────────────
  867: "Parabrachial nucleus. Integrates pain, taste, thermosensory, and visceral information; the critical ascending relay for interoceptive signals to the forebrain.",
  123: "Kölliker-Fuse nucleus. Part of the lateral parabrachial complex; a key node for respiratory pattern generation, particularly controlling inspiratory-expiratory phase transitions.",

  // ── Locus coeruleus and noradrenergic ─────────────────────────────────────
  147: "Locus coeruleus. Primary noradrenergic nucleus; regulates arousal, attention, cognitive flexibility, and the stress response.",
  283: "Lateral tegmental nucleus. Contains noradrenergic A1 and A2 neurons; involved in cardiovascular regulation and autonomic control.",
  350: "Subceruleus nucleus. Located ventral to the locus coeruleus; contains noradrenergic A7 neurons; involved in REM sleep generation and descending motor regulation.",
  358: "Sublaterodorsal nucleus. Key generator of REM sleep; produces the muscle atonia characteristic of REM sleep.",

  // ── Pontine and medullary reticular formation ──────────────────────────────
  280: "Barrington's nucleus. Contains the sole neurons driving bladder voiding; also involved in defecation and pelvic organ coordination.",
  1048:"Gigantocellular reticular nucleus. The largest reticular nucleus in the medullary RF; the primary origin of reticulospinal fibers; involved in locomotion, posture, and somatic motor facilitation.",
  136: "Intermediate reticular nucleus. Medullary reticular region involved in autonomic and motor regulation; coordinates swallowing, respiration, and other rhythmic behaviors.",
  307: "Magnocellular reticular nucleus. Pontine reticular nucleus; involved in postural and somatic motor control.",
  1098:"Medullary reticular nucleus, dorsal part. Medullary reticular region involved in descending motor control via the reticulospinal tract.",
  1107:"Medullary reticular nucleus, ventral part. Medullary reticular region involved in motor and autonomic regulation.",
  995: "Paramedian reticular nucleus. Small medullary nucleus involved in cerebellar control of eye movements.",
  852: "Parvicellular reticular nucleus. Part of the medullary reticular formation involved in swallowing, respiration, and autonomic regulation.",
  970: "Paragigantocellular reticular nucleus, dorsal part. Located adjacent to the gigantocellular nucleus; involved in autonomic and motor regulation.",
  978: "Paragigantocellular reticular nucleus, lateral part. Contains pre-sympathetic neurons and noradrenergic A1 cells; involved in cardiovascular regulation and descending pain modulation.",
  1093:"Pontine reticular nucleus, caudal part. Part of the paramedian pontine reticular formation (PPRF); involved in generating horizontal saccades.",
  146: "Pontine reticular nucleus. Rostral part of the PPRF; involved in horizontal gaze control and postural regulation.",
  574: "Tegmental reticular nucleus. Pontine precerebellar nucleus; involved in motor coordination.",
  1069:"Parapyramidal nucleus. Small serotonergic nucleus near the pyramidal tract in the medullary base; involved in motor and autonomic regulation.",
  604: "Nucleus incertus. Contains relaxin-3-expressing neurons; involved in stress responses, arousal, and hippocampal theta rhythm regulation.",

  // ── Locus coeruleus-adjacent ───────────────────────────────────────────────
  318: "Supragenual nucleus. Small nucleus in the pontine dorsal tegmentum involved in motor coordination and vestibular integration.",

  // ── Colliculi ──────────────────────────────────────────────────────────────
  811: "Inferior colliculus, central nucleus. Primary auditory midbrain nucleus; performs binaural processing, sound localization, and spectrotemporal analysis.",
  820: "Inferior colliculus, dorsal nucleus. Higher-order auditory nucleus involved in multisensory integration and auditory learning.",
  828: "Inferior colliculus, external nucleus. Multimodal nucleus; a key site for auditory-motor and sensorimotor integration.",
  580: "Nucleus of the brachium of the inferior colliculus. Relay nucleus between the inferior colliculus and medial geniculate complex; involved in auditory thalamic processing.",
  271: "Nucleus sagulum. Part of the lateral lemniscal system; involved in auditory processing.",
  851: "Superior colliculus, optic layer. Drives visual orienting reflexes toward salient stimuli.",
  842: "Superior colliculus, superficial gray layer. Primary visual input layer; responds to luminance and contrast; drives visual orienting reflexes.",
  834: "Superior colliculus, zonal layer. Superficial visual layer of the superior colliculus.",
  10:  "Superior colliculus, intermediate gray layer (motor-related). Integrates visual, auditory, and somatosensory information to generate orienting movements of the head and eyes.",
  17:  "Superior colliculus, intermediate white layer (motor-related). Contains efferent fibers conveying orienting movement commands to brainstem premotor circuits.",
  26:  "Superior colliculus, deep gray layer (motor-related). Coordinates head and body orientation movements.",
  42:  "Superior colliculus, deep white layer (motor-related). White matter layer carrying motor output from the deep SC.",
  874: "Parabigeminal nucleus. Cholinergic nucleus adjacent to the brachium of the superior colliculus; modulates SC activity and visual attention.",

  // ── Pretectum ──────────────────────────────────────────────────────────────
  215: "Anterior pretectal nucleus. Involved in descending pain modulation; electrical stimulation produces analgesia; also involved in attention and defensive behavior.",
  706: "Olivary pretectal nucleus. The primary mediator of the pupillary light reflex; driven by intrinsically photosensitive retinal ganglion cells.",
  634: "Nucleus of the posterior commissure. Part of the pretectal region; involved in the coordination of vertical eye movements.",
  1061:"Posterior pretectal nucleus. Part of the pretectal area involved in visual and oculomotor reflexes.",
  628: "Nucleus of the optic tract. Drives compensatory eye movements (optokinetic nystagmus) in response to whole-field visual motion.",

  // ── Accessory optic system ─────────────────────────────────────────────────
  66:  "Lateral terminal nucleus of the accessory optic system. Detects optic flow signals; drives the optokinetic reflex to stabilize gaze during self-motion.",

  // ── Zona incerta and subthalamic region ───────────────────────────────────
  797: "Zona incerta. Subthalamic GABAergic nucleus that gates and coordinates sensory, motor, and limbic processing; regulates feeding, attention, defensive behaviors, and rhythmic motor patterns.",

  // ── Auditory brainstem ─────────────────────────────────────────────────────
  96:  "Dorsal cochlear nucleus. Processes complex auditory features including spectral notches used for sound localization in elevation.",
  101: "Ventral cochlear nucleus. Initial processing of auditory timing, frequency, and intensity; three pathways mediate binaural processing for sound localization.",
  112: "Granular lamina of the cochlear nuclei. Intermediate layer between the dorsal and ventral cochlear nuclei involved in auditory processing.",
  560: "Cochlear nucleus, subpeduncular granular region. Part of the cochlear nucleus complex involved in auditory processing.",
  642: "Nucleus of the trapezoid body. Critical for encoding interaural time differences for low-frequency sound localization.",
  612: "Nucleus of the lateral lemniscus. Auditory nucleus on the ascending pathway; involved in binaural processing and temporal coding.",
  90:  "Nucleus of the lateral lemniscus, horizontal part. Part of the lateral lemniscal complex involved in binaural auditory processing.",
  99:  "Nucleus of the lateral lemniscus, ventral part. Processes auditory timing information.",
  114: "Superior olivary complex, lateral part. Computes interaural level differences for high-frequency sound localization.",
  105: "Superior olivary complex, medial part. Binaural coincidence detector for interaural time differences; critical for low-frequency sound localization.",
  122: "Superior olivary complex, periolivary region. Provides efferent olivocochlear feedback; modulates cochlear gain and sensitivity.",
  887: "Efferent cochlear group. Neurons providing direct efferent innervation to cochlear hair cells; modulates outer hair cell motility and cochlear sensitivity.",

  // ── Trigeminal system ──────────────────────────────────────────────────────
  7:   "Principal sensory nucleus of the trigeminal. Processes discriminative touch from the face; the facial analog of the dorsal column nuclei.",
  429: "Spinal nucleus of the trigeminal, caudal part. Processes pain and temperature from the face and oral cavity; analogous to the superficial spinal cord dorsal horn; a key relay for orofacial pain and headache.",
  437: "Spinal nucleus of the trigeminal, interpolar part. Processes deep pain from teeth and temporomandibular joint; involved in dental pain and headache pathways.",
  445: "Spinal nucleus of the trigeminal, oral part. Processes orofacial mechanoreception and nociception; important for jaw reflexes and orofacial pain.",
  460: "Midbrain trigeminal nucleus. Contains the cell bodies of primary proprioceptive afferents from jaw muscles; the only location in the CNS where primary sensory neuron cell bodies reside (outside the dorsal root ganglia).",
  534: "Supratrigeminal nucleus. Located dorsal to the motor trigeminal nucleus; involved in jaw-opening reflexes and coordination of masticatory rhythm.",
  621: "Motor nucleus of the trigeminal. Contains motor neurons innervating the muscles of mastication (masseter, temporalis, pterygoids, digastric); controls chewing movements.",

  // ── Cranial motor nuclei ───────────────────────────────────────────────────
  661: "Facial motor nucleus. Contains motor neurons innervating all muscles of facial expression via the facial nerve (CN VII); organized into subnuclei for different facial regions.",
  576: "Accessory facial motor nucleus. Small accessory group of facial motoneurons associated with the facial motor nucleus.",
  653: "Abducens nucleus. Contains motor neurons for the lateral rectus muscle; controls horizontal eye movements.",
  568: "Accessory abducens nucleus. Small accessory group adjacent to the abducens nucleus; may contribute to retraction of the globe and eyelid movements.",
  35:  "Oculomotor nucleus. Contains motor neurons for four extraocular muscles (medial, superior, inferior recti and inferior oblique) and levator palpebrae; controls vertical and medial eye movements.",
  115: "Trochlear nucleus. Contains motor neurons for the superior oblique muscle; the only cranial nerve to exit the brainstem dorsally; controls intorsion and depression of the adducted eye.",
  975: "Edinger-Westphal nucleus. Contains preganglionic parasympathetic neurons; controls pupillary constriction and lens accommodation.",
  67:  "Interstitial nucleus of Cajal. Part of the vertical gaze holding network; integrates eye velocity signals to maintain vertical and torsional eye position.",
  587: "Nucleus of Darkschewitsch. Involved in vertical gaze control and coordination of eye movements.",
  773: "Hypoglossal nucleus. Contains motor neurons innervating all tongue muscles via the hypoglossal nerve (CN XII); critical for swallowing, chewing, and speech articulation.",
  143: "Nucleus ambiguus, ventral division. Contains motor neurons for pharyngeal and laryngeal muscles via CN IX and X; critical for swallowing and vocalization.",
  939: "Nucleus ambiguus, dorsal division. Contains parasympathetic preganglionic neurons controlling heart rate; also innervates soft palate.",
  839: "Dorsal motor nucleus of the vagus nerve. Contains preganglionic parasympathetic neurons; regulates heart rate, respiratory rate, and gastrointestinal motility via the vagus nerve.",
  106: "Inferior salivatory nucleus. Contains preganglionic parasympathetic neurons for the parotid gland via the glossopharyngeal nerve (CN IX); controls salivation.",

  // ── Nucleus of the solitary tract and area postrema ───────────────────────
  651: "Nucleus of the solitary tract. Primary visceral sensory relay nucleus; processes cardiovascular, respiratory, and gastrointestinal signals.",
  859: "Parasolitary nucleus. Small nucleus adjacent to the NTS involved in visceral sensory integration.",
  207: "Area postrema. Circumventricular organ lacking a blood-brain barrier; serves as the chemoreceptor trigger zone for vomiting; detects blood-borne toxins, emetic drugs, and hormones.",

  // ── Vestibular nuclei ──────────────────────────────────────────────────────
  225: "Spinal vestibular nucleus. Processes vestibular signals related to body rotation and head position; contributes to postural control via the vestibulospinal tract.",
  202: "Medial vestibular nucleus. Integrates vestibular and visual signals to generate the vestibuloocular reflex (VOR) and gaze stabilization.",
  209: "Lateral vestibular nucleus. Contains Deiters' neurons; the origin of the lateral vestibulospinal tract; provides powerful facilitation of extensor motor neurons for postural control.",
  217: "Superior vestibular nucleus. Processes semicircular canal input; contributes to eye movement stabilization and postural reflexes.",
  640: "Efferent vestibular nucleus. Provides efferent feedback to hair cells of the vestibular labyrinth; modulates the sensitivity of vestibular afferents.",

  // ── Olivary and precerebellar ──────────────────────────────────────────────
  83:  "Inferior olivary complex. The sole source of cerebellar climbing fibers that synapse on Purkinje cells; encodes motor errors and timing signals critical for cerebellar motor learning and coordination.",
  955: "Lateral reticular nucleus, magnocellular part. Precerebellar nucleus involved in limb movement coordination.",
  963: "Lateral reticular nucleus, parvicellular part. Precerebellar nucleus involved in conveying motor signals to the cerebellum.",
  931: "Pontine gray. The largest precerebellar nucleus; relays motor and cognitive information to the cerebellar hemispheres; critical for voluntary movement coordination.",

  // ── Other medullary ────────────────────────────────────────────────────────
  203: "Linear nucleus of the medulla. Small medullary nucleus; TBD specific function.",
  169: "Nucleus prepositus. Neural integrator for horizontal gaze holding; maintains eye position by integrating eye velocity signals.",
  161: "Nucleus intercalatus. Small medullary nucleus near the solitary tract; involved in integrating eye movement and visceral signals.",
  177: "Nucleus of Roller. Part of the hypoglossal complex; involved in tongue movement coordination.",

  // ── Cerebellar deep nuclei ─────────────────────────────────────────────────
  846: "Dentate nucleus. The largest deep cerebellar nucleus; critical for voluntary limb movement, cognitive processing, and motor learning.",
  91:  "Interposed nucleus. Deep cerebellar nucleus between the dentate and fastigial nuclei; involved in correcting limb movements during reaching.",
  989: "Fastigial nucleus. Deep cerebellar nucleus; controls trunk, axial muscles, and gaze.",
  372: "Infracerebellar nucleus. Small nucleus located below the cerebellum; TBD specific function.",

  // ── Cerebellar cortex ──────────────────────────────────────────────────────
  1056:"Crus 1 (ansiform lobule). Lateral cerebellar hemisphere lobule; involved in higher cognitive functions and coordination with associative cortex.",
  1064:"Crus 2 (ansiform lobule). Lateral cerebellar hemisphere lobule; involved in cognitive processing, fine motor control, and communication with the cerebral cortex.",
  1049:"Flocculus. Part of the vestibulocerebellum; critical for vestibuloocular reflex (VOR) adaptation and smooth pursuit eye movements.",
  1041:"Paraflocculus. Adjacent to the flocculus; involved in VOR and optokinetic reflex control.",
  912: "Lingula (lobule I). The most anterior vermal lobule; involved in proprioceptive processing and trunk control.",
  976: "Lobule II. Anterior vermal lobule; involved in proprioception and somatosensory integration.",
  984: "Lobule III. Anterior vermal lobule; part of the spinocerebellar territory for proprioceptive processing.",
  1091:"Lobules IV–V (culmen). Anterior vermal lobules; involved in coordination of limb movements.",
  936: "Declive (lobule VI). Posterior vermal lobule; involved in visuomotor control.",
  944: "Folium-tuber vermis (lobule VII). Posterior vermal lobule; involved in cerebellar integration of somatosensory information.",
  951: "Pyramis (lobule VIII). Posterior vermal lobule; involved in cerebellar processing of somatosensory and vestibular signals.",
  957: "Uvula (lobule IX). Posterior vermal lobule; involved in balance and postural control.",
  968: "Nodulus (lobule X). Part of the vestibulocerebellum; involved in responses to head tilt, otolith signals, and optokinetic responses.",
  1033:"Copula pyramidis. Posterior lobe hemisphere region adjacent to the pyramis; involved in motor coordination.",
  1025:"Paramedian lobule. Hemisphere lobule adjacent to the vermis; involved in limb coordination.",
  1007:"Simple lobule. Hemisphere lobule; involved in limb movement control.",

  // ── Small/specialized nuclei ───────────────────────────────────────────────
  765: "Nucleus x. Small vestibular-related nucleus near the superior vestibular nucleus; TBD specific function.",
  781: "Nucleus y. Part of the paramedian tract group; involved in eye movement control and vestibular integration.",
  789: "Nucleus z. Located at the medulla-spinal cord junction; part of the dorsal column-medial lemniscal pathway for upper limb proprioception.",
  898: "Pontine central gray. Gray matter surrounding the pontine tegmentum; involved in autonomic and behavioral state regulation.",
};
